version: '3.8'
services:
    mongodb:
        image: mongo:4.4-bionic
        container_name: jump-DB
        ports: 
            - 27017:27017
        volumes:
            - mongodb--vol:/data/db
            - ./db/mongo-init/:/docker-entrypoint-initdb.d/:ro

    services:
        image: santohi/jumpse:latest
        container_name: jump-SE
        extra_hosts:
            - "localhost:192.168.65.2"
        ports:
            - 5001:5001
        environment: 
            - SERVER_PORT=5001
            - SERVER_URL=0.0.0.0
            - API_ITEMS=http://localhost:5000/api/items/create

    back_end:
        image: santohi/jumpbe:latest
        container_name: jump-BE
        extra_hosts:
            - "localhost:192.168.65.2"
        depends_on: ["mongodb"]
        ports: 
            - 5000:5000
        environment: 
            - SERVER_PORT=5000
            - SERVER_HOSTNAME=localhost
            - MONGO_USERNAME=silviu
            - MONGO_PASSWORD=ASD123asd>
            - MONGO_HOST=sarus.uvxdn.mongodb.net/sarus?retryWrites=true&w=majority

    front_end:
        image: santohi/jumpfe:latest
        container_name: jump-FE
        extra_hosts:
            - "localhost:192.168.65.2"
        ports: 
            - 3000:80
        environment: 
            - REACT_APP_API_SEARCH=http://localhost:5000/api/search
            - REACT_APP_API_SEARCH_CREATE=http://localhost:5000/api/search/create
            - REACT_APP_API_SEARCH_DELETE=http://localhost:5000/api/search/delete
            - REACT_APP_API_ITEMS_DELETE=http://localhost:5000/api/items/delete
            - REACT_APP_API_SCRAP=http://localhost:5001/task
# in-service volumes are very slow in MacOS and Windows, 
# so using fast shared volumes for large storage
volumes:
    mongodb--vol: